### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by OhioVR** [DanielnetoDotCom/YouPHPTube-Encoder#101]
Hello,
I've been working on getting large file encoding to work and I'm experiencing this error in the logs as it hangs up during upload in the encoder:

Out of memory (allocated 2378461184) (tried to allocate 2374266096 bytes) in /var/www/html/objects/Encoder.php on line 235

I looked at line 235 in that script and it is doing this:
if (file_put_contents($obj->pathFileName, $response)) {

It would seem that file_put_contents requires the object to be entirely in ram and the file Is bigger than the whole amount of ram on my virtual machine. 

Is this a known problem with the code? I don't see how a configuration change can help in this problem.

**Comment by DanielnetoDotCom** [comment]
you will need more memory RAM 

we describe it here https://github.com/DanielnetoDotCom/YouPHPTube/wiki/About-Video-Upload#ram-memory

**Comment by OhioVR** [comment]
Monitor the file upload process in the encoder's video directlry using 

watch ls -l 

and you will see a file such as "original_SpiesLikeUs19851080pBluRayx264DTSFGT_YPTuniqid_5c137fa3d10e37.95139340"

completely uploads before any feed back appears in the encoder web page. There is no reason to load it into memory that I can see. You could copy it, or even symlink it to your temp file. The file is already there.

**Comment by DanielnetoDotCom** [comment]
But in many times encoder and streamers are in different servers

**Comment by OhioVR** [comment]
I am referring to the initial upload process. As the file goes up to the encoder and by extention it's own video encoder file directory, it will make it there 100% before any feed back occurs. If you start an upload, the entire file always makes it to the server unless there is no hard drive room left, it doesn't matter if you have 2x the system memory of the file or 1/2x it always successfully uploads the whole thing. I have made a video demonstration so you can see what I mean:

https://www.youtube.com/watch?v=JUkxtKRMomQ

**Comment by DanielnetoDotCom** [comment]
@OhioVR thanks for your clarification. maybe this process can be improved, but let me explain why I didn't figure out a way to do it yet.

We have many ways to send videos to the encoder, we can use other sites videos, "bulk encode" for videos that are already in your and upload. All those methods goes to the queue.

After you upload and generate the original file this file will hanging there waiting for its time to be encoded on the queue list.

when its time comes, they call the same function https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/blob/e46e78ec595214897bb928041aff205b6e573104/objects/Encoder.php#L201

this function will decide if will use YouTube DL or will download the video directly, on the upload case will download it directly .

Conclusion, the original file is the way I found to store the uploaded file wait its time do be encoded.
the tmpFile it the "Downloaded file" that will be used to be encoded.

**Comment by DanielnetoDotCom** [comment]
I guess if you drop many files on the upload it will create many original files and 1 tmpfile at a time

**Comment by OhioVR** [comment]
I have confirmed my fork fails to work with the bulk encoding function. I had not tried it before till now so that is probably why it escaped my testing.

**Comment by DanielnetoDotCom** [comment]
I see, thanks for testing, maybe we can find a solution for both, keep the old way for bulk and your way to the uploaded.

do you have a partial solution already in your fork?

maybe you can share or pull request here

**Comment by OhioVR** [comment]
Hi Daniel,

I found that the reason my fork was failing to encode the bulk encode lists was because it was symlinking the video directory instead of the source directory. I've pushed my changes and submitted a pull request for it. Here is a video of my tests:

https://www.youtube.com/watch?v=AeAv2pncEB0

**Comment by OhioVR** [comment]
A new pull request for this issue has been posted that can be merged. (I didn't have some upstream changes registered in there at that time).
