### ISSUE TITLE
Permission Denied to Receive a File: Array

### ISSUE THREAD

**Issue by tbailey1712** [DanielnetoDotCom/YouPHPTube-Encoder#103]
Hello, fresh install of YouPHPTube and the Encoder.  If I upload a file directly to the encoder, it is throwing an error in the log.  Not sure where the permissions are that need fixed.  Any suggestions?

---

[14-Dec-2018 10:11:53 America/xx] YouPHPTube-Encoder sending file to http://encoder.xx.com/YouPHPTube/youPHPTube
Encoder.json
[14-Dec-2018 10:11:53 America/xx] YouPHPTube-Encoder reading file from /var/www/html/YouPHPTube-Encoder/videos/5_tmpFile
_converted_SD.mp4
[14-Dec-2018 10:11:53 America/xx] YouPHPTube-Streamer answer {"error":true,"msg":"Permission denied to receive a file: A
rray\n(\n    [duration] => 0:05:56\n    [title] => FILE\n    [videos_id] => 0\n    [categories_id] => 0\n
 [format] => mp4\n    [resolution] => SD\n    [videoDownloadedLink] => \n    [description] => \n    [user] => admin\n    [pas
sword] => ___\n)\n"}
[14-Dec-2018 10:11:53 America/xx] {"error":false,"format":"mp4","file":"\/var\/www\/html\/YouPHPTube-Encoder\/videos\/5_
tmpFile_converted_SD.mp4","resolution":"SD","videoDownloadedLink":null,"target":"http:\/\/encoder.xx.com\/YouPHPTube\
/youPHPTubeEncoder.json","postFields":11,"videoFileSize":"81.18MB","response_raw":"{\"error\":true,\"msg\":\"Permission denie
d to receive a file: Array\\n(\\n    [duration] => 0:05:56\\n    [title] => FILE\\n    [videos_id] => 0\\n
  [categories_id] => 0\\n    [format] => mp4\\n    [resolution] => SD\\n    [videoDownloadedLink] => \\n    [description] =>
\\n    [user] => admin\\n    [password] => ___\\n)\\n\"}","response":{"error":true,"msg":"Permis
sion denied to receive a file: Array\n(\n    [duration] => 0:05:56\n    [title] => FILE\n    [videos_id] =>
0\n    [categories_id] => 0\n    [format] => mp4\n    [resolution] => SD\n    [videoDownloadedLink] => \n    [description] =>
 \n    [user] => admin\n    [password] => ___\n)\n"}}

**Comment by tbailey1712** [comment]
password is the same for admin on both the streamer and the encoder.

Logged off / on / even rebooted.

Still happening

**Comment by DanielnetoDotCom** [comment]
If you update your streamer, make sure you also update your encoder

**Comment by tbailey1712** [comment]
What do you mean by update?  Just uploading videos?

And if I did update my streamer, please tell me what I do should do to update my encoder. Perhaps that will fix the issue.

**Comment by DanielnetoDotCom** [comment]
You need to have the latest files.versions on your encoder as well.

Make a git pull on your encoder

**Comment by tbailey1712** [comment]
That seemed to work. Did a git pull on both directories and an Apache restart. Thanks for the suggestions.

**Comment by DanielnetoDotCom** [comment]
Great

**Comment by tbailey1712** [comment]
And....now it's happening again after the latest git pull.  Do I need to do something to update the passwords so they are stored in a hash?  Looks like they are plantext in configuration.php

[20-Dec-2018 10:06:11 America/xx] Password check new hash pass does not match, trying MD5
[20-Dec-2018 10:06:11 America/xx] Password check Old encoded pass
[20-Dec-2018 10:06:11 America/xx] Password check Old not found
[20-Dec-2018 10:06:11 America/xx] ReceiveImage: Permission denied to receive a file: Array

**Comment by DanielnetoDotCom** [comment]
looks like you are having a problem with the hash.

did you enable or disable or change the salt?

try to generate your password with MD5 and replace the one on the database.

![image](https://user-images.githubusercontent.com/18009293/50336656-692fa080-04ed-11e9-8899-f1ca2f83c4ae.png)
