### ISSUE TITLE
Login Fails, wrong handling in function url_get_contents

### ISSUE THREAD

**Issue by dheule** [DanielnetoDotCom/YouPHPTube-Encoder#111]
Hi, we have tracked a probem in function url_get_contents. 

This function is called from Login with a stream context set ( do a POST and form data to login).

But in the original function the execution path leads to
```
 fetch_http_file_contents($Url);
``` 
**Attention here the context is ignored (leads to GET instead of post)**
**if url_allow_fopen is on**
**else to curl handling with the same problem that the context is ignored.**

if an exception would be thrown, the correct call to file_get_contents with the correct context is made (but a wrong GET request do not generate an exception.

So please see the diff to change the order (first call file_get_contents with context, if fails call the complex  path without the context file)

```
diff --git a/objects/functions.php b/objects/functions.php
index 8783c8c..f8ad73d 100644
--- a/objects/functions.php
+++ b/objects/functions.php
@@ -62,13 +62,13 @@ function url_get_contents($Url, $ctx = "") {

     if (ini_get('allow_url_fopen')) {
         try {
-            fetch_http_file_contents($Url);
+            $tmp = @file_get_contents($Url, false, $context);
+            if ($tmp != false) {
+                return $tmp;
+            }
         } catch (ErrorException $e) {
             try {
-                $tmp = @file_get_contents($Url, false, $context);
-                if ($tmp != false) {
-                    return $tmp;
-                }
+                fetch_http_file_contents($Url);
             } catch (ErrorException $e) {
                 error_log("Error on get Content");
             }
@@ -610,4 +610,4 @@ function ip_is_private($ip) {
 function encryptPassword($password, $streamerURL) {
     $streamerEncrypt = json_decode(url_get_contents("{$streamerURL}objects/encryptPass.json.php?pass=". urlencode($password)));
     return $streamerEncrypt->encryptedPassword;
```

**Comment by DanielnetoDotCom** [comment]
Hi, do you have it modified on your side?
why don't you make a pull request so we can merge versions?

**Comment by dheule** [comment]
done, see pr #112

**Comment by DanielnetoDotCom** [comment]
thanks
