### ISSUE TITLE
I can't connect to encoder server

### ISSUE THREAD

**Issue by zhongxi2** [DanielnetoDotCom/YouPHPTube-Encoder#115]
can't connect to encoder server.
its show pop up message.
Sorry!
Connect Error (2002) Connection refused

![encoder_error](https://user-images.githubusercontent.com/47232212/52096662-fe54a780-260a-11e9-94bb-6a7fe99341e5.jpg)

**Comment by DanielnetoDotCom** [comment]
it looks like for me a database error

**Comment by zhongxi2** [comment]
> it looks like for me a database error

Ok, Its database error. solved already thanks.

**Comment by DanielnetoDotCom** [comment]
you welcome, if you can, please share your solution
