### ISSUE TITLE
video upload file hangs at ~70%

### ISSUE THREAD

**Issue by nbenm** [DanielnetoDotCom/YouPHPTube-Encoder#116]
I have encoded a mkv to mp4 with ffmpeg.
I have already used this way of encoding.
When I upload the file to my server, it starts well, but hangs at nearly 70%.
There's no message in the log file.
Any idea ?

**Comment by nbenm** [comment]
I've found an error message. It wasn't in the youphptube.log file, it was in the apache log file.
I have increased max_execution_time and max_input_time values, and it works now.
Changing only one of them wasn't sufficient.
I don't know if this is the best way to solve the problem.

**Comment by DanielnetoDotCom** [comment]
Thanks for the update
