### ISSUE TITLE
Admin cannot remove other user's queue's

### ISSUE THREAD

**Issue by hersche** [DanielnetoDotCom/YouPHPTube-Encoder#12]
hello,

I think as admin, it should be possible to see and cancel other jobs as admin.

The problematic thing is: when it hangs, the admin has to run around for the right user for continue.

Hanging queues, which aren't issues in my eyes, can come from reboots of the server - then it will not continue since the processes are killed of course.

Anyway, if the admin can do what's a admin role is for, the problems are solved :)

best regards and thx for your efforts

vinzenz

**Comment by DanielnetoDotCom** [comment]
Hi, should have a problem there, Admins can cancel any job.

In my case the admin user from tutorial site is the admin. It can cancel any job

![image](https://user-images.githubusercontent.com/18009293/32032922-ea178172-b9df-11e7-8b6c-7c73b7dbfa16.png)

**Comment by hersche** [comment]
oh, nice, thanks for the screenshot and very quick answer - i see that i don't have the tabs configurations, update and streamers in my instance, also with admin-login - cause i was not admin on the encoder. 

found the value in the db, so fixed.
