### ISSUE TITLE
encoder only can see queue and queue log two tabs

### ISSUE THREAD

**Issue by nfsiv** [DanielnetoDotCom/YouPHPTube-Encoder#124]
good day Daniel,

tonight i build up a new site as live environment, 2 servers one for stream one for encoder, but after my encoder site up, after login by admin account i can only see queue and log tab, other 3 tab will not dispaly.

in my mind all setup steps are same as my lab environment, and i did the setup for the encoder server twice all same.

so could you guide me some?

thanks

**Comment by nfsiv** [comment]
just an update, i go into the encoder server's database, manually change the streamers table, set the isAdmin value is 1, then solved. but i still do not know why my site configed but isAdmin is 0. please have a look then let me know where is my mistake. thanks

**Comment by DanielnetoDotCom** [comment]
the admin user is by (username and domain), not by streamer.

if you changed the admin user name or the domain (i.e. adding or remove www) it will not be encoder admin animore
