### ISSUE TITLE
Incorrect AJAX to listFiles.json is 404

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [DanielnetoDotCom/YouPHPTube-Encoder#129]
Let me explain the background. I have my encoder behind a reverse proxy, `example.com/video` is my streamer site (apache behind a nginx reverse proxy) and `example.com/video/encoder` is my encoder (also apache behind a nginx reverse proxy but on a different machine). My reverse proxy looks like this:
```
  location ~/video(.*)$
  {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $host;
    proxy_pass https://192.168.0.70/web-apps/video$1$is_args$args;
    include /etc/nginx/includes/ip-exclude.conf;

    location ~/video/encoder(.*)$
    {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $host;
    proxy_pass https://192.168.0.28/encoder$1$is_args$args;
    include /etc/nginx/includes/ip-exclude.conf;
    }
  }
```

When using the bulk encoder feature no files are listed because the AJAX call is sent to `video/encoder/listFiles.json` which is a 404.

This is fixed by editing line 588 in `views/index.php`.
```
                        $.ajax({
                            url: 'listFiles.json',
```
to
```                       
                        $.ajax({
                            url: 'view/listFiles.json.php',
```

I don't know if this is an issue with my proxy.

**Comment by Engineer-of-Stuff** [comment]
Solved it. For some reason my `.htaccess` had the streamer one and not the proper encoder one.

**Comment by Engineer-of-Stuff** [comment]
I'm reopening this so the dev sees this.

I noticed that I was getting `413 Request Entity Too Large` error in my encoder logs. Can you add a warning on the install page or wiki that lets people know to increase `client_max_body_size` to something larger in the nginx config?

**Comment by DanielnetoDotCom** [comment]
Is it an NGINX or APACHE issue?

**Comment by Engineer-of-Stuff** [comment]
Nginx. The proxy needs to have the same large post_max_size and upload_max_filesize.

My setup is 
nginx proxy <=> apache (php) server

**Comment by DanielnetoDotCom** [comment]
I always install it on apache, I can not help you on Nginx installation
