### ISSUE TITLE
Not recognizing Encoder Problem

### ISSUE THREAD

**Issue by Joket-Dev** [DanielnetoDotCom/YouPHPTube-Encoder#132]
Hi,

While I installing the YouPHPTubeEncoder, I checked it recognize the encoder "ffmpeg".
But when I upload video, an error occurs while encoding video.

In temp_FileProgress.txt file, it says, "sh: ffmpeg: command not found".

I think it is concerned with the owner of ffmpeg.

In addition I logged in as root user.

And I checked ffmpeg works in terminal.

How can I do with this problem?

**Comment by DanielnetoDotCom** [comment]
you can ignore it and try to install.
