### ISSUE TITLE
Add requirement php7.1-xml for Ubuntu 18.04 installation

### ISSUE THREAD

**Issue by noslenkwah** [DanielnetoDotCom/YouPHPTube-Encoder#133]
Just installed the encoder on a fresh Ubuntu Server 18.04 VM. It required `php7.1-xml` to get rid of the "PHP Fatal error: Uncaught Error: Call to undefined function utf8_encode()" error.

`sudo apt-get install php7.1-xml`

It would be useful to include it in the [instructions](https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x---For-YouPHPTube-Encoder).

**Comment by DanielnetoDotCom** [comment]
Thanks, it was added
