### ISSUE TITLE
Blank page after installation

### ISSUE THREAD

**Issue by Sugiramireille** [DanielnetoDotCom/YouPHPTube-Encoder#17]
Dear YouPHPTube, I am writting this to share with you a problem that occured to me and how I resolved it. You may see a blank page after you hit the install button of YouPHPTube. One of the reason may be the one I faced. Go to youphptube.log located in the videos folder. If you find an error message like this 

> PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): 
Then it is an issue with timezone in your PHP.ini file. Locate your PHP ini file and input your time zone. Php official time zones can be found here: http://php.net/manual/en/timezones.africa.php 

I am new to this, but i have a feeling I will realize my dream. So I can't stop sharing my findings and tips. I don't this is the right place to post this. I apologize in any case.

Thanks.

**Comment by DanielnetoDotCom** [comment]
Hi try this https://stackoverflow.com/questions/35455315/uncaught-exception-exception-with-message-datetime-construct

**Comment by Sugiramireille** [comment]
Thanks Daniel, I was able to resolve that way. Thanks
