### ISSUE TITLE
Not converting

### ISSUE THREAD

**Issue by christianreiss** [DanielnetoDotCom/YouPHPTube-Encoder#19]
Hey folks,

Fresh Install on CentOS7 (fresh vm) using PHP 7.1. Both sites (streamer and encoder) and up and accessible, but uploading any video to the encoder immediately gets halted with
```
[20-Nov-2017 15:35:28 UTC] MP4 All
[20-Nov-2017 15:35:28 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
[20-Nov-2017 15:35:28 UTC] YouPHPTube-Encoder sending file to https://example.com/youPHPTubeEncoder.json
[20-Nov-2017 15:35:28 UTC] YouPHPTube-Encoder reading file from 
```
The file(s) are uploaded correctly, however and have the right permissions. I am not entirely sure why it would fail and why the Filename would be empty "()".

Secondly,
how are transcode jobs triggered? I could not find any sort of middleware or cron file on the encoder anywhere.

Thanks for you support! <3
-Chris,

**Comment by DanielnetoDotCom** [comment]
I guess it can be permissions.
How did u put the file there, did u upload or use a video link to download?

The key to the job trigger is the Encoder::run(); method

**Comment by christianreiss** [comment]
Hey, 
Thanks for replying!
```
total 820K
drwxr-xr-x 2 apache apache  118 Nov 20 17:09 .
drwxr-xr-x 4 root   root     35 Nov 20 15:40 ..
-rw-r--r-- 1 apache apache  583 Nov 20 17:08 configuration.php
-rw-r--r-- 1 apache apache 809K Nov 20 17:09 original_20171012114002_YPTuniqid_5a12fe2d350b90.04032200
-rw-r--r-- 1 apache apache  340 Nov 20 17:09 youphptube.log
```
Looks good to me; I did upload them via "Upload" button from the encoder web ui.

**Comment by DanielnetoDotCom** [comment]
strange, but I can see one thing, configuration.php should have rights to execute.
I do not have many ideas what can it be.

**Comment by DanielnetoDotCom** [comment]
Also if you can take a look on that https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/issues/7

**Comment by christianreiss** [comment]
Hey,

I have **not** solved this issue. I however, created two docker images using Ubuntu and your installation instructions leading to a up-and-running Installation of youphptube, complete with the Encoder.

```
docker run -d --restart=always -p 9880:80 -v /local/path/to/store/videos:/var/www/html/videos --name youphptube creiss/al-youphptube
docker run -d --restart=always -p 9881:80 -v /local/path/to/store/encoder_videos:/var/www/html/videos --name youphptube-encoder creiss/al-youphptube-encoder
```
8 seconds later, youphptube will be up and running on Port 9880 and youphptube-encoder running on 9881. Launch nginx in front of it and you're all set to go.

Encoding et all works like a charm. As I am no longer concerned with a CentOS installation I am closing this issue now.

Could not be easier.
-Chris.
