### ISSUE TITLE
Error during Encoder instalation

### ISSUE THREAD

**Issue by mariu1986** [DanielnetoDotCom/YouPHPTube-Encoder#2]
During encoder instalation i have error : 

Unknown column 'allowedStreamersURL' in 'field list'

Could you help please ?

**Comment by mariu1986** [comment]
instalation link
http://ballbustingbondagebdsm.pl/YouPHPTube-Encoder-master/install/index.php

**Comment by mariu1986** [comment]
Steamer link is:
http://www.ballbustingbondagebdsm.pl/YouPHPTube-master/

**Comment by mariu1986** [comment]
solved, sorry, i created new database

**Comment by mariu1986** [comment]
hmm, but this encoder don't work today

**Comment by DanielnetoDotCom** [comment]
hi, it suppose to work
What is the problem?
give me more details

**Comment by mariu1986** [comment]
Errors:
Execute code error Array ( ) Code: ffmpeg -i /home/mar1986/ftp/YouPHPTube-Encoder-master/videos/2_tmpFile.mp4 -vf scale=-2:480 -vcodec h264 -acodec aac -strict -2 -y /home/mar1986/ftp/YouPHPTube-Encoder-master/videos/2_tmpFile_converted.mp4

Please see link to my encoder:
http://ballbustingbondagebdsm.pl/YouPHPTube-Encoder-master/
user test
password test

**Comment by DanielnetoDotCom** [comment]
If you copy and paste this code on your server terminal, what is the output?

`ffmpeg -i /home/mar1986/ftp/YouPHPTube-Encoder-master/videos/2_tmpFile.mp4 -vf scale=-2:480 -vcodec h264 -acodec aac -strict -2 -y /home/mar1986/ftp/YouPHPTube-Encoder-master/videos/2_tmpFile_converted.mp4`

**Comment by mariu1986** [comment]
server terminal ?

**Comment by mariu1986** [comment]
don't have i tihnk

**Comment by DanielnetoDotCom** [comment]
Yes you probably use ssh to access your server.
To have the encoder you must have root access to the server

Em 14 de ago de 2017 20:32, "mariu1986" <notifications@github.com> escreveu:

**Comment by mariu1986** [comment]
i don't see anything, did you seen info in configuration when you log in ?

**Comment by mariu1986** [comment]
i am log in to database througth phpMyAdmin
when i paste this code in console inside database i have a sereval errors

**Comment by mariu1986** [comment]
in config we have errors:
1 - MP4 ffmpeg -i {$pathFileName} -vf scale=-2:480 -vcodec h264 -acodec aac -strict -2 -y {$destinationFile}

2 - Webm ffmpeg -i {$pathFileName} -vf scale=-2:360 -f webm -c:v libvpx -b:v 1M -acodec libvorbis -y {$destinationFile}

3 - MP3 ffmpeg -i {$pathFileName} -acodec libmp3lame -y {$destinationFile}

4 - OGG ffmpeg -i {$pathFileName} -acodec libvorbis -y {$destinationFile}

5 - MP3 to Spectrum.MP4 ffmpeg -i {$pathFileName} -filter_complex '[0:a]showwaves=s=640x360:mode=line,format=yuv420p[v]' -map '[v]' -map 0:a -c:v libx264 -c:a copy {$destinationFile}

6 - Video.MP4 to Audio.MP3 ffmpeg -i {$pathFileName} -y {$destinationFile}

**Comment by mariu1986** [comment]
i tried on different hosting and this same error

**Comment by DanielnetoDotCom** [comment]
It is not and sql command, it is an shell command line 
You must paste it on your Linux server terminal

**Comment by mariu1986** [comment]
I looking for additional terminal yesterday and today, but i don't have it in phpMyAdmin

**Comment by DanielnetoDotCom** [comment]
It is not in phpmyadmin you must check with your host provider if you have ssh access

**Comment by mariu1986** [comment]
ok, i logged by program PuTTY

when i paste "ffmpeg -i /home/mar1986/ftp/YouPHPTube-Encoder-master/videos/2_tmpFile.mp4 -vf scale=-2:480 -vcodec h264 -acodec aac -strict -2 -y /home/mar1986/ftp/YouPHPTube-Encoder-master/videos/2_tmpFile_converted.mp4"

i have only info:
-bash: ffmpeg: command not found

mar1986@mar1986:~$ ffmpeg -i /home/mar1986/ftp/YouPHPTube-Encoder-master/videos/2_tmpFile.mp4 -vf scale=-2:480 -vcodec h264 -acodec aac -strict -2 -y /home/mar1986/ftp/YouPHPTube-Encoder-master/videos/2_tmpFile_converted.mp4
-bash: ffmpeg: command not found

**Comment by DanielnetoDotCom** [comment]
That is why you must install ffmpeg
Try this tutorial https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x---For-YouPHPTube-version-3.x-or-older

**Comment by mariu1986** [comment]
ehhh :(, when i past code
sudo apt-get install apache2 php7.0 libapache2-mod-php7.0 php7.0-mysql php7.0-curl php7.0-gd php7.0-intl mysql-server mysql-client ffmpeg git libimage-exiftool-perl

in terminal i must type password i think
[sudo] password for mar1986:

but what password ? my password for login to this terminal don't work here

**Comment by DanielnetoDotCom** [comment]
you need a root password.
Your host provider must give you this or ask them to install FFMPEG for you

**Comment by mariu1986** [comment]
on another hosting which support FFMPEG it works, upload correctly, but in configuration panel in encoder we can still see a errors:
1 - MP4 ffmpeg -i {$pathFileName} -vf scale=-2:480 -vcodec h264 -acodec aac -strict -2 -y {$destinationFile}

2 - Webm ffmpeg -i {$pathFileName} -vf scale=-2:360 -f webm -c:v libvpx -b:v 1M -acodec libvorbis -y {$destinationFile}

3 - MP3 ffmpeg -i {$pathFileName} -acodec libmp3lame -y {$destinationFile}

4 - OGG ffmpeg -i {$pathFileName} -acodec libvorbis -y {$destinationFile}

5 - MP3 to Spectrum.MP4 ffmpeg -i {$pathFileName} -filter_complex '[0:a]showwaves=s=640x360:mode=line,format=yuv420p[v]' -map '[v]' -map 0:a -c:v libx264 -c:a copy {$destinationFile}

6 - Video.MP4 to Audio.MP3 ffmpeg -i {$pathFileName} -y {$destinationFile}

**Comment by DanielnetoDotCom** [comment]
I do not think it is an error
is that scree you are talking about?

![image](https://user-images.githubusercontent.com/18009293/29384237-bad3d31a-82a9-11e7-84f7-2e118d9944f9.png)

**Comment by mariu1986** [comment]
yes, it is not error :) ?
it is correct ?

**Comment by mariu1986** [comment]
then solved :) of course
