### ISSUE TITLE
Encoder stuck on Uploading

### ISSUE THREAD

**Issue by ChrisEHOliver** [DanielnetoDotCom/YouPHPTube-Encoder#22]
Setup the encoder server, no errors appearing, but when on the encoder server when uploading a file, it goes to 100% of the progress circle, and sits at Uploading.....

**Comment by DanielnetoDotCom** [comment]
Hi, the same happened on public encoder? https://encoder.youphptube.com/
Can you check the encoder and the streamer log file?

**Comment by ChrisEHOliver** [comment]
Thanks.. from another article is saw that someone was missing the libimage-exiftool-perl and was having issues. Guess we missed that.
So ran sudo apt-get install apache2 php7.0 libapache2-mod-php7.0 php7.0-mysql php7.0-curl php7.0-gd php7.0-intl mysql-server mysql-client ffmpeg git libimage-exiftool-perl
And now everything is working.
Thanks
