### ISSUE TITLE
Few things ive noticed so far and id like to request

### ISSUE THREAD

**Issue by soolhami** [DanielnetoDotCom/YouPHPTube-Encoder#23]
Hey guys

Great work here many kudos

Issue one thumbnails between resolution and aspect ratio break the theme display and get cut off for me anyways. Is this a streamer or encoder issue, upon inspection of the code the col class shows all thumbs at 216x180

Issue two how to send video to the appropriate stream site, again for me anyways afaik it always defaults to the one installation no matter what url the encoder is called from.

Hope this all makes sense please advise if clarity is needed
Thanks

**Comment by DanielnetoDotCom** [comment]
Hi, 

1) Yes the thumbs is generated in a fixed size. it may be improved in the future.

2) the encoder sends the video to the user account you used to login on it. for example. if you login on the encoder with the **test** user account from demo site, the encoder will send the video to demo site and **test** user will be video the owner.

**Comment by soolhami** [comment]
Okay thanks for that i've managed to get the encoder install to send thee videos to the appropriate streamer by using different usernames (both were admin) Another thing i've noticed with the thumbs in gallery view, the theme itself is quite dependent on the window size and looks good and uniform if not in full screen perhaps i will play with the margins. Anyways thanks again!!
