### ISSUE TITLE
Information video when imported youtube video

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube-Encoder#26]
Hello there, 

so now i started importing video from youtube, that's very cool, i take it only in HD.

can we get more information from youtbe, exemple the original link in the description of the video, the real author, the key word of the video, other stuff

what do u think about this ?

thanks

**Comment by DanielnetoDotCom** [comment]
I think it is a great Idea, I will try to import more things 

Take a look on this, I think some of those features are included on here https://github.com/DanielnetoDotCom/YouPHPTube/issues/293https://github.com/DanielnetoDotCom/YouPHPTube/issues/293
