### ISSUE TITLE
YouPHPTube-Encoder - blocked - Bulk not working to

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube-Encoder#27]
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/files/1600032/youphptube.log)
Hello there, 

so i have tried to import some videos from youtube : 
so i put a files yesterdayt and he is still in my encoder with no movement : 
![image](https://user-images.githubusercontent.com/32466950/34516940-3b744fe4-f079-11e7-9d5f-0346aaae34d5.png)

nothing in queue : 
![image](https://user-images.githubusercontent.com/32466950/34516927-2e11caf2-f079-11e7-9caa-cd282e0d87f6.png)

can u please explain me, how works the encoder and why my download is like this and no way to move it ?

i paste my log encoder files

when we have a problem here in encoder, how reset the list of queu ?

thanks

**Comment by DanielnetoDotCom** [comment]
hi, looks like you have a ploblem on the first file.
just delete the file, on the queue log, to the encoder continue.
take a look on your youphptube.log file from your encoder to check what happened

**Comment by gamersalpha** [comment]
i thinki broke myinstallation, my video are not imported in youphptube.domaine.Fr :'(

since i change to use https with auto sogned certificat so a wrong certificat

no stable installation 

i think 
i will reinstall evrythink in http  and use i reverse proxy to secure this
