### ISSUE TITLE
Just an idea - For Youtube - Sync user with youtube channel

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube-Encoder#29]
Hello, 
so my idea is create an account and sync all video of this account on u personal YouPHPTUBE, 

The idea is evrytime the youtube User add a new Video the video is automaticly downloaded on u personal youPHPTUBE, and u have a notification of u personal YouPHPtube, 

gens de venir sur notre YouPHPTUBE.

qu'en pensez vous ? Modifier

The technique is to give people envy to come on our YouPHPTUBE.

What do you think ?

**Comment by DanielnetoDotCom** [comment]
that is a good idea and maybe will be implemented in the future
