### ISSUE TITLE
no way to upluoad mp4 video

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube-Encoder#32]
Hello there, i m trying to upluoad some mp4 video come from Obs studios (i hope is near futur i can make a streaming and directly recorded my video on my youPHPTUBe)
for now i ulpuaad the video manyally, but i can't .
i have no error message nothing 👍 
just this : 
![image](https://user-images.githubusercontent.com/32466950/35778420-56c4c6b2-09be-11e8-86b7-b5a0befd73f7.png)

what do u think please ?

**Comment by DanielnetoDotCom** [comment]
@gamersalpha hi, you can direct record stream: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Record-Live-Stream

About the upload error, take a look on the streamer log file
