### ISSUE TITLE
Fatal error on PHP 7.2.2

### ISSUE THREAD

**Issue by Knah-Tsaeb** [DanielnetoDotCom/YouPHPTube-Encoder#33]
Hi,
with PHP 7.2.2 I have :

```Fatal error: Cannot use 'Object' as class name as it is reserved in /mnt/http/encode.local/objects/Object.php on line 8```

**Comment by DanielnetoDotCom** [comment]
Just send a Fix, please test it

**Comment by Knah-Tsaeb** [comment]
That's work.
Thanks.
