### ISSUE TITLE
converting ip to domain url

### ISSUE THREAD

**Issue by harshak79** [DanielnetoDotCom/YouPHPTube-Encoder#34]
Hi Folks, 

I was able to successfully install Youphptube. However there is a small issue I am facing the current url is something like http://<ip>/YouPHPTube/ how do I convert it to a domain something like www.example.com. I have already added a DNS A record for www.example.com, but when I browse it gives the default apache page and if I try to append the url like "example.com/YouPHPTube/ "  . I get the below error in screen shot. Can some one help me with this. So basically if I browse www.example.com I should be able to see YouPHPTube screen.  
<img width="949" alt="screen shot 2018-02-15 at 12 21 41 pm" src="https://user-images.githubusercontent.com/32215448/36244101-d5a7184c-124a-11e8-86a9-a639a6adbbb8.png">

**Comment by DanielnetoDotCom** [comment]
try to use virtual hosts on apache

https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-14-04-lts
