### ISSUE TITLE
Not support for PHP 5.4.5?

### ISSUE THREAD

**Issue by baalchina** [DanielnetoDotCom/YouPHPTube-Encoder#35]
In Server Requirements sector, it says PHP 5.3+ is OK.

But when I install, server tolds me 

>  Your PHP version is 5.4.45, you must install PHP 5.6.x or greater 

So, maybe the readme.md shoud change? :)

Thanks.

**Comment by DanielnetoDotCom** [comment]
Yes you right I will change readme
