### ISSUE TITLE
Got Unknown error when install

### ISSUE THREAD

**Issue by baalchina** [DanielnetoDotCom/YouPHPTube-Encoder#36]
Hi, when I tried to install youphptube-encode in my Ubuntu 16.04, all check in the left windows passed(Apache, PHP, php.ini, and etc), but when click submit, a dialog told me  sorry, Unknown error.

So, is there any log to find this error?

Thanks.

**Comment by DanielnetoDotCom** [comment]
What is your database name 
Try to look apache error log

**Comment by baalchina** [comment]
Thanks. But Apache error log got nothing.
My db name is 'sql10_100_176_1', a auto generate name by my control panel.  Maybe this is the problem?

**Comment by DanielnetoDotCom** [comment]
Make sure you select only to create tables and do not create database

**Comment by baalchina** [comment]
That works, thanks!
