### ISSUE TITLE
Question about large file and temp file in encoder

### ISSUE THREAD

**Issue by baalchina** [DanielnetoDotCom/YouPHPTube-Encoder#37]
Hi, just installed YouPHPTube-Encode, and I have two questions, needs help.

1, when I upload file, youphptube-encode told me
```
The encoder Max File Size is: 100.00MB 
The Streamer Max File Size is: 100.00MB 
The Streamer Max Video Storage Limit is: Unlimited 
The Streamer Current Video Storage is: 38.53 Minutes
```
And I tried files larger than 100MB, of course can not upload.

So, is this max file size is in php.ini? If I want to upload larger files, how can I do?
And,  the `Streamer Max File Size` means the size of video file can not larger than this value?

2, After encode finished, the origin file and temp file should be deleted or not in YouPHP-Encode? I found still some mp4 file such as `7_tmpFile_converted_HD.mp4` in YouPHP-Encode's video folder. Is this normal?

Thanks.

**Comment by DanielnetoDotCom** [comment]
Hi yes it is a php.ini configuration

And yes you can delete the file from encoder after finish

**Comment by baalchina** [comment]
thanks. Maybe encode can delete the temp file automaticly， that will be great.

**Comment by brajeshrgupta** [comment]
Hi

I have set the file size to 1GB but file size of about 200MB is not uploading. some files of 100mb to 120MB are uploaded but JPG and GIF files are not generated also HD file is not generated.

Please help

**Comment by loso20p** [comment]
anyway to make the encoder compress a large file and decrease the size and have hd quality like openload

**Comment by DanielnetoDotCom** [comment]
@loso20p you can increase your server max post/file size on your php.ini

**Comment by loso20p** [comment]
yes i know that but i was asking if u can reduce the file size because the encoder makes a 300 mb  into a 2.8 g file and thats crazy. so i was wondering if it can reduce a large size like that site openload does and maintain the quality

**Comment by DanielnetoDotCom** [comment]
check the FFMPEG script and reduce the resolution or change parameters.
Check FFMPEG manual for options to compress files

![image](https://user-images.githubusercontent.com/18009293/37300551-02c90632-2605-11e8-877f-7e4e1c6d0607.png)

**Comment by loso20p** [comment]
thats interesting my encoder only says  Encoding Queue
 Queue Log i dont see configuration update or streamer like in ur image

**Comment by DanielnetoDotCom** [comment]
Check your encoder database, streamer table, the column isAdmin of your user must be = 1

![image](https://user-images.githubusercontent.com/18009293/37301390-3289c468-2607-11e8-86dd-9a82472f96bb.png)

**Comment by loso20p** [comment]
o ok

**Comment by DanielnetoDotCom** [comment]
Great
