### ISSUE TITLE
Fresh install - Endless "Processing" when doing configuration

### ISSUE THREAD

**Issue by BDaddyG** [DanielnetoDotCom/YouPHPTube-Encoder#38]
Hello
New Ubuntu 16.04 server and fresh GIT pull and configuration of the Encoder (fresh Streamer site config'd fine).

After satisfying all requirements and entering site details on the install page, I press Submit and Processing is displayed but doesn't finish.

I reinstalled the Streamer site and I noticed that on the configuration page the SQL port was listed, but on the Encoder configuration page this option was missing.  Could that be my issue?

Thanks!

**Comment by DanielnetoDotCom** [comment]
Can you please look the apache log to see what happened ?

Also by default the script creates a database make sure that database does NOT exists before the installation process

**Comment by BDaddyG** [comment]
Verified that the database doesn't exist.

I didn't see anything in the Apache log, but in the MySQL log I found:

2018-02-20T01:51:55.357770Z 2 [Note] Access denied for user 'root'@'localhost' (using password: NO)
2018-02-20T01:51:55.417584Z 3 [Note] Access denied for user 'root'@'localhost' (using password: NO)

I've also verified I typed the SQL root user password in the "Database Password" field (didn't leave it blank)

**Comment by DanielnetoDotCom** [comment]
That is why, your database user and pass does not match

**Comment by BDaddyG** [comment]
I'm using "root" for the "Database User" field and entering the correct password in the "Database Password" filed.

**Comment by DanielnetoDotCom** [comment]
Can you create another user or change the password?
I am afraid there are some characters, in your password, that is massing up the connection

**Comment by BDaddyG** [comment]
I can, but the password is:  VideoSQL    (test box, don't care if anyone knows the password at this point) so there are no special characters

**Comment by DanielnetoDotCom** [comment]
it not suppose to give errors, are you sure you can connect? and this root user have create database rights?

you also have options to create only tables, check the dropdown menu

**Comment by BDaddyG** [comment]
Just verified I can connect to the MySQL server with:  mysql -u root -p    and entering the password.

I tried manually creating the database using the "create only tables" option but had the same result "endless Processing"

**Comment by DanielnetoDotCom** [comment]
For now I have no Idea why your password is not being submited to the script

**Comment by BDaddyG** [comment]
Is there a way I can pull an older version of the Encoder with GIT?  I could see if I have the same issue.

**Comment by DanielnetoDotCom** [comment]
I guess you do, search on google.

But could you install the streamer on the same server?

**Comment by BDaddyG** [comment]
Yes, streamer installed without issue on the same server.

**Comment by DanielnetoDotCom** [comment]
I really want to find what is the problem, is your server online, would you like to give me your ssh credentials to test it?

**Comment by DanielnetoDotCom** [comment]
I can not do it now, but send me a email with details developer@youphptube.com

**Comment by djprmf** [comment]
I have the same problem...
CentOS, endless processing. MySQL databases are not being created even witha  simple password.
BTW, im using MariaDB (but is the same as MySQL, so shouldn't be any problem from that). I don't get any mysql error though...

**Comment by danikuci1** [comment]
Same.

I'm using a brand spanky new ubuntu 16.04 and followed the instructions on the wiki.

I also get an ` Access denied for user 'root'@'localhost' (using password: NO)` which is odd, because password logins are enabled and I've input the correct password into the youphptube installer. Does the installer pass the password to mysql correctly?

**Comment by DanielnetoDotCom** [comment]
for some reason, looks like your password was not submited.
can you please debug to make sure the connection is using your password?

**Comment by danikuci1** [comment]
my password was definitely input into the form, and can verify it works from console. I've tried with different browser also.

is there a particular log I should look at?

**Comment by DanielnetoDotCom** [comment]
Look the apache log

**Comment by danikuci1** [comment]
yes, the password I was using does include special characters. i will create a new user and password that doesnt.

here is the excerpt from the apache log:
```
[Wed Mar 07 11:08:18.165402 2018] [core:notice] [pid 3508] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 07 11:08:36.605901 2018] [:error] [pid 3520] [client 10.0.0.185:62050] PHP Warning:  require_once(/var/www/encode/view/../videos/configuration.php): failed to open stream: No such file or directory in /var/www/encode/view/index.php on line 7
[Wed Mar 07 11:08:36.605939 2018] [:error] [pid 3520] [client 10.0.0.185:62050] PHP Fatal error:  require_once(): Failed opening required '/var/www/encode/view/../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/encode/view/index.php o$
[Wed Mar 07 11:08:36.625868 2018] [:error] [pid 3520] [client 10.0.0.185:62050] PHP Warning:  mkdir(): Permission denied in /var/www/encode/objects/functions.php on line 77
[Wed Mar 07 11:09:54.999009 2018] [mpm_prefork:notice] [pid 3508] AH00169: caught SIGTERM, shutting down
[Wed Mar 07 11:09:56.161942 2018] [mpm_prefork:notice] [pid 3631] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Wed Mar 07 11:09:56.162022 2018] [core:notice] [pid 3631] AH00094: Command line: '/usr/sbin/apache2'
```
the permissions error seems a bit odd to me, since www-data owns the directory and it passes the pre-check.

**Comment by danikuci1** [comment]
seems to be generating those same PHP errors over and over again:
```
[Wed Mar 07 11:22:32.552798 2018] [:error] [pid 3635] [client 10.0.0.185:62107] PHP Warning:  require_once(/var/www/encode/view/../videos/configuration.php): failed to open stream: No such file or directory in /var/www/encode/view/index.php on line 7
[Wed Mar 07 11:22:32.552843 2018] [:error] [pid 3635] [client 10.0.0.185:62107] PHP Fatal error:  require_once(): Failed opening required '/var/www/encode/view/../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/encode/view/index.php o$
```

www-data definitely owns the directory:
```
dani@YouPHPTube2:/var/www$ ls -la encode/
total 88
drwxr-xr-x 9 www-data www-data  4096 Mar  7 11:09 .
drwxr-xr-x 5 root     root      4096 Mar  7 11:05 ..
-rwxr-xr-x 1 www-data www-data  1776 Mar  7 11:04 .htaccess
-rwxr-xr-x 1 www-data www-data  3797 Mar  7 11:04 index.php
drwxr-xr-x 2 www-data www-data  4096 Mar  7 11:04 install
-rwxr-xr-x 1 www-data www-data 34520 Mar  7 11:04 LICENSE
drwxr-xr-x 2 www-data www-data  4096 Mar  7 11:04 model
drwxr-xr-x 2 www-data www-data  4096 Mar  7 11:04 nbproject
drwxr-xr-x 2 www-data www-data  4096 Mar  7 11:04 objects
-rwxr-xr-x 1 www-data www-data  4626 Mar  7 11:04 README.md
drwxr-xr-x 2 www-data www-data  4096 Mar  7 11:04 update
drwxr-xr-x 2 www-data www-data  4096 Mar  7 11:09 videos
drwxr-xr-x 8 www-data www-data  4096 Mar  7 11:04 view
```

want me to try different permissions? or I could manually run the DB script before the main installer?

**Comment by DanielnetoDotCom** [comment]
Try to give write permition in your videos dir

`chmod +w /var/www/encode/videos/`

**Comment by danikuci1** [comment]
alright I was able to get it to work.

here's what I did:

1.  I was originally trying to use an account other than root for mysql. I had created an empty DB and an account and given that account full permissions to that DB. This is the same way I installed the streamer site, and that was sufficient for it. Apparently it is not sufficient for the encoder site. Might want to look into your DB scripts and see what the difference is and why it is working that way.

2.  I changed the root password to not use special characters. My previous password contained both `@` and `!`

this will work for me fine for testing purposes, although i'd kinda like to configure it with more restrictive settings in the future. my ultimate goal is to create a small private site for friends and family where we can share videos of our kids doing cute stuff mainly.

**Comment by DanielnetoDotCom** [comment]
I am glad it is working now, and thanks for your solution description

**Comment by BDaddyG** [comment]
I'm still have this issue.

Tried again tonight with a fresh Ubuntu server 16.04 build.

My Apache error.log has the following:

[Thu Mar 08 22:03:37.119793 2018] [:error] [pid 14222] [client 172.16.1.184:40634] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/YouPHPTube-Encoder/view/../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/html/YouPHPTube-Encoder/view/index.php on line 7

**Comment by DanielnetoDotCom** [comment]
Try to give write permition in your videos dir

`chmod +w /var/www/YouPHPTube-Encoder/videos/`

**Comment by sethuper** [comment]
I have exacly the same issue when I want to install youphptube-encoder or youphptube-encoder-network.

I have installed YouPHPTube on Debian 10 with no problems.
But when I tried to install YouPHPTube-Encoder or YouPHPTube-Encoder-Network, installation stucks on "processing" - I have checked logs and it looks like there is an error in script:
"PHP Warning: require_once(/var/www/YouPHPTube/YouPHPTube-Encoder/view/../configuration.php): failed to open stream: No such file or directory".
I searched on the internet to solve this problem but there is nothing about it at all.
It is not a server problem: distribution, www, php, mysql, permisions etc.. its an instalation script.
this file: /var/www/YouPHPTube/upload/objects/Login.php.
this line cause the problem:
require_once dirname(__FILE__) . '/../configuration.php';
but if I remove "/../" - there is no more problem with missing file - output:
/var/www/YouPHPTube/YouPHPTube-Encoder/view/configuration.php
but after editing and removing "/../" there is bigger problem:
Uncaught Error: Call to a member function query() on null in.. ..objects/Object.php:35\nStack trace:\n#0 .. objects/Object.php(13): ObjectYPT::getFromDb(1)\n#1 etc.
Could you look at these problem please, I wish I could use it for may dashcam videos - for personal use and for friends away from youtube.
Debian10, apache2.4, php7.0 and 7.3, mariadb10.3.22, permission for www-data.
Directory YouPHPTube - /var/www/YouPHPTube/
Directory YouPHPTube-Encoder - /var/www/YouPHPTube/YouPHPTube-Encoder/

Thank you.
