### ISSUE TITLE
Unknown encoder error ... in conversion

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube-Encoder#39]
Switching to a new server installed on Ubuntu 16.04 around the control panel VestaCP ... the Streamer works, but the encoder when I have to download from Youtube gives me this unknown error in the encoder ... in conversion, with the result that the conversion is stops (it does not finish anymore).

Further down, one extracted from the encoder's log:

`[08-Mar-2018 12:49:21 UTC] MP4 `
`[08-Mar-2018 12:49:21 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}`
`[08-Mar-2018 12:49:21 UTC] YouPHPTube-Encoder sending file to https://www.abc.eu/youPHPTubeEncoder.json`
`[08-Mar-2018 12:49:21 UTC] YouPHPTube-Encoder reading file from `
`[08-Mar-2018 12:49:23 UTC] YouPHPTube-Streamer answer {"error":false,"video_id":303}`
`[08-Mar-2018 12:49:23 UTC] {"error":false,"format":"mp4","file":"","resolution":"","target":"https:\/\/www.abc.eu\/youPHPTubeEncoder.json","postFields":9,"response_raw":"{\"error\":false,\"video_id\":303}","response":{"error":false,"video_id":303}}`
`[08-Mar-2018 12:49:23 UTC] Getting from Youtube DL youtube-dl  --force-ipv4 --no-check-certificate -k -o /tmp/youtubeDlX2e9BC.mp4 -f 'mp4' https://www.youtube.com/watch?v=abcdef`
`[08-Mar-2018 12:49:31 UTC] runMultiResolution`
`[08-Mar-2018 12:49:31 UTC] YouPHPTube-Encoder Start Encoder [ffmpeg -i /home/bcda/web/e1.abc.eu/public_html/videos/4_tmpFile.mp4 -vf scale=1280:720 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y /home/bcda/web/e1.abc.eu/public_html/videos/4_tmpFile_converted_HD.mp4] `
`[08-Mar-2018 12:50:21 UTC] PHP Warning:  Error while sending QUERY packet. PID=4462 in /home/bcda/web/e1.abc.eu/public_html/objects/Format.php on line 29`
`[08-Mar-2018 12:50:21 UTC] PHP Notice:  Undefined property: stdClass::$code in /home/bcda/web/e1.abc.eu/public_html/objects/Encoder.php on line 427`
`[08-Mar-2018 12:50:21 UTC] stdClass `
`(`
` [error] => 1
    [msg] => Execute code error Code not found (, /home/bcda/web/e1.abc.eu/public_html/videos/4_tmpFile.mp4, /home/bcda/web/e1.abc.eu/public_html/videos/4_tmpFile_converted_Low.mp4, 4) 
 Code: 
)
`

**Comment by DanielnetoDotCom** [comment]
Looks like it is regarding your MySQL `PHP Warning: Error while sending QUERY packet`

Check this https://stackoverflow.com/questions/30753674/error-while-sending-query-packet

**Comment by tgd1973** [comment]
I saw the error ... and in fact it seems to me that there maybe a database error but I did not believe it ... and that's why I wrote.
Unlike ISPConfig which installs by default Mariadb .. this panel VestaCP installs Mysql ... and from here, the error ...
I had to edit in /etc/mysql/my.cnf, the parameters:
max_allowed_packet = 64M
wait_timeout=60

and now it seems that it works ... but I still do not understand the connection between the encoding process and the database ...

**Comment by DanielnetoDotCom** [comment]
Encoder and Streamer database is required.

**Comment by DanielnetoDotCom** [comment]
I am glad it is working now.

**Comment by DanielnetoDotCom** [comment]
Great, thanks for sharing your solution
