### ISSUE TITLE
Bulk Encode not add in queue

### ISSUE THREAD

**Issue by deivisonmoraes** [DanielnetoDotCom/YouPHPTube-Encoder#4]
![bulk encode](https://user-images.githubusercontent.com/5691097/29335534-63a63ad8-81e1-11e7-91e5-be2fa5bba317.png)

Do I need to do anything else?

Tks

**Comment by DanielnetoDotCom** [comment]
After put your address , 
1 - click on the List Files buttons, 
2 - and check all videos you want to encode
![image](https://user-images.githubusercontent.com/18009293/29337597-33ebcbe4-81e8-11e7-836d-dd60e244658c.png)

**Comment by deivisonmoraes** [comment]
Ok. I'll test Thanks! 

[]'s

**Comment by deivisonmoraes** [comment]
Is it possible to somehow select the resolutions I want to make encode? For me 1 movie of 1.4Gb is taking many hours to finish the conversion to webm in 360.

**Comment by deivisonmoraes** [comment]
Funcionou perfeitamente. Tomei mais cuidado com espaços.
