### ISSUE TITLE
New serveur Encoder problem installation - Blocking a Cross-Origin Request: The "Same Origin" 

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube-Encoder#44]
Hello there, i have a problem with my new encoder serveur install : 

in french : 

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://youtube.namel.fr//login. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.

google traduction : 

`Blocking a Cross-Origin Request: The "Same Origin" policy does not allow you to view the remote resource located on https://youtube.namel.fr//login. Reason: The CORS header "Access-Control-Allow-Origin" is missing.
`

i m the installation page :  i m using Firefox Dev to see log error : 

![image](https://user-images.githubusercontent.com/32466950/37873572-a2b6e5f0-301f-11e8-81b1-dff60f75acf7.png)

i make some seearch about this error, 

it's look like u can make a ajax request an other domain of u website who u make the requete ?

for me : 

youphptube site is :  https://youtube.domaine.fr
youtphptube-encoder is https://youtube-encoder.domaine.fr

so i m go in the installer page and i have this erro ?

what is wrong please ?

**Comment by DanielnetoDotCom** [comment]
Hi actually you can, but your server must be configured to allow it

we add the .htaccess configuration to allow this request

https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/blob/bb8dc65c448130fa142b3ff235298b8b5d6ea908/.htaccess#L1

https://github.com/DanielnetoDotCom/YouPHPTube/blob/50caf7409aae152a7ac3c9255b0d7fb251871c36/.htaccess#L16

It works on our side, maybe the server you are using have an specific configuration to block it

**Comment by gamersalpha** [comment]
Hello, 

i m using nginx to access to my server in https.

revers proxy, works cool, 

i have to found how pass this problem

**Comment by gamersalpha** [comment]
crazy thinks i can't found a solution :'(

**Comment by gamersalpha** [comment]
do u have a solution to create the config files without the internet page ?

can i create myself the config please ?

can someone send me the config files, i will modifie it and adding directly on my video directory

thanks to all

**Comment by DanielnetoDotCom** [comment]
My Encoder config file looks like this:
...
```
<?php
$global['webSiteRootURL'] = 'http://127.0.0.1/YouPHPTube-Encoder/';
$global['systemRootPath'] = '/var/www/html/YouPHPTube-Encoder/';

$global['disableConfigurations'] = false;
$global['disableBulkEncode'] = false;

$mysqlHost = 'localhost';
$mysqlUser = 'root';
$mysqlPass = '';
$mysqlDatabase = 'youPHPTube-Encoder';

$global['allowed'] = array('mp4', 'avi', 'mov', 'mkv', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv');

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';
```

**Comment by FathiBenNasr** [comment]
Thank you,
This solved my same problem here (+ manual tables creation).

**Comment by DanielnetoDotCom** [comment]
Great :)

**Comment by gamersalpha** [comment]
ok where is the databas creation files please

**Comment by gamersalpha** [comment]
i have  a blank page with no information

u closed to fast

**Comment by DanielnetoDotCom** [comment]
Database creation https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/blob/master/install/database.sql

Check your log file for the blank page

**Comment by gamersalpha** [comment]
ok works with this but i have a new problem here

the same here -- https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/issues/44
