### ISSUE TITLE
É possível desabilitar a conversão para webm?

### ISSUE THREAD

**Issue by deivisonmoraes** [DanielnetoDotCom/YouPHPTube-Encoder#5]
Verifiquei que mesmo enviando o video em mp4 ele converte para mp4 em 480. Depois disso ele faz a conversão para 360 em webm. É possível fazer algo para que ele só converta para 480 ou apenas para 360? 
O motivo da pergunta é que busco soluções para diminuir o tempo de conversão. Meu servidor físico tem 16 GB de ram 2 HDs de 2 TB em raid 1 processador de 8 nucleos de 2.8  #Ghz.

[]'s

**Comment by DanielnetoDotCom** [comment]
Olá

Você pode editar as configurações e adicionar o comando -threads [num de núcleos]
dá uma olhada em https://superuser.com/questions/792525/how-to-change-ffmpeg-threads-settings
Este comando vai fazer você usar mais núcleos para a conversão, por padrão o ffmpeg usa apenas 1 núcleo.
isso vai acelerar bastante sua conversão 

![image](https://user-images.githubusercontent.com/18009293/29384108-423c1a66-82a9-11e7-8324-bbf7ea05a5cb.png)

**Comment by deivisonmoraes** [comment]
No meu encoder não aparece essa oplão de configuração... Como faço para ativa-la? 

Obrigado pelo retorno!

**Comment by DanielnetoDotCom** [comment]
Veja se no banco de dados na tablea de streamers se seu usuário esta marcado como admin

**Comment by deivisonmoraes** [comment]
Não estava. Logo que coloquei apareceu. Sobre desativar um dos formatos, seria possível?

[]'s

**Comment by DanielnetoDotCom** [comment]
você pode tentar reduzir a resolução do webm, isso fará ele codificar muito mais rapido
por exemplo: ffmpeg -i {$pathFileName} -vf scale=-2:**60** -f webm -c:v libvpx -b:v 1M -acodec libvorbis -y {$destinationFile}

**Comment by deivisonmoraes** [comment]
Ok. Analisando meu gráfico de processamento me parece que o mp4 usa todos os processadores. Adicionei o esquema dos núcleos para ver como fica o tempo. Depois vou reduzir a resolução para ver como fica.

**Comment by deivisonmoraes** [comment]
Gerei um com a resolução 60 com você sugeriu. Porem observei que o está sendo reproduzido pelo streamer é exatamente ela, nesse caso ficou com a qualidade muito ruim. Como é feita a escolha do vídeo que o streamer irá disponibilizar? Já que ele gera 2 opções?

**Comment by DanielnetoDotCom** [comment]
A opção de qual versão o stramer irá usar depende do navegador. alguns navegadores usam o MP4 e outros o WEBM, por isso o YouPHPTube codifica os 2 formatos, para manter a compatibilidade

**Comment by deivisonmoraes** [comment]
Entendi. Obrigado! Vou fechar o issue.

**Comment by duduxweb** [comment]
Aproveitando esse posto é possível upar já em .Webm ?

**Comment by DanielnetoDotCom** [comment]
por enquanto não, mas o WebM é compatível apenas com alguns navegadores, o MP4 é melhor

**Comment by DinhoUnisul** [comment]
Ola vou aproveitar post porque o meu problema é parecido, eu criei o meu próprio encoder porem quando termino de fazer upload da um erro.
[https://imgur.com/a/Gm36Bax](url)

**Comment by DanielnetoDotCom** [comment]
@DinhoUnisul seu erro nao me disse muita coisa, mas agora você pode desabilitar a conversão WebM 

adicione a variavel abaixo no seu arqiovo configuration.php;
`
$global['disableWebM'] = 1;`
