### ISSUE TITLE
Auto Remove not working

### ISSUE THREAD

**Issue by cbuchmannNM** [DanielnetoDotCom/YouPHPTube-Encoder#51]
I have an issue regarding the auto remove feature.
Even though the the feature is enabled, no files are getting deleted.
I am able to delete files as user www-data in the videos location of the encoder and the return code of rm is 0.
The Encoder has been updated from 2.1 to 2.3 before. On a test Server with a fresh install the autodelete feature is working perfectly.

![sql_configurations](https://user-images.githubusercontent.com/38256644/38881000-533fa89a-4267-11e8-8e5f-22f12e3203a6.PNG)

![www-data_user_shell](https://user-images.githubusercontent.com/38256644/38881202-d3f41b9c-4267-11e8-8c7d-20f7407929e2.PNG)

[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/files/1920565/youphptube.log)

**Comment by DanielnetoDotCom** [comment]
Hi

Are you saying the updated encoder version is not working, but I new installation is working correct?

Please try to update your files, I sent a fix regarding it yesterday.

**Comment by cbuchmannNM** [comment]
Hi,
everything is working now, after I've updated the live server.
I would never have thought to check for another update, as I've updated the live server and installed the test server practically in short of a hour.
Thank you very much.
