### ISSUE TITLE
different videos show when clicked 

### ISSUE THREAD

**Issue by joey2354** [DanielnetoDotCom/YouPHPTube-Encoder#56]
hi there ... when i click on this link https://potads-vids.ml/video/vancouver-420-2018-live-from-sunset-beach it shows the wrong video.

it seems to be showing this one https://potads-vids.ml/video/the-rick-simpson-story-healing-cancer-with-cannabis-more-at-cureyourowncancer-org-

is a bug on your side ? or have i done something wrong here ?

thank you. 

edit: they all are now, they seem to showing the second linked vid above  on all the videos.

**Comment by DanielnetoDotCom** [comment]
very strange, can you check on the database if the embed links are not the same?
Looks like fore some reason you change the embed link of one of them

**Comment by DanielnetoDotCom** [comment]
really really strange.

can I try to update your server files to see how it works?

**Comment by joey2354** [comment]
can u ?  yes i guess if that's what u thinks right .. you're the boss :)

**Comment by DanielnetoDotCom** [comment]
Can you please email me an admin user for your site, before I update it?

**Comment by joey2354** [comment]
sent it buddy :)

**Comment by DanielnetoDotCom** [comment]
Hi Joe, I update your site and still the same, but I had a look into your database, and as I suspect the links are all the same.

![image](https://user-images.githubusercontent.com/18009293/39143090-2181a16e-4703-11e8-9e1f-8e9bddbf1ac5.png)

I can only imagine it was manually changed, I have no idea how it happend

**Comment by joey2354** [comment]
ok well that is strange because i haven't done it.

ok so what happens now ?

**Comment by DanielnetoDotCom** [comment]
You can remove the repeated videos and put them again

**Comment by joey2354** [comment]
ok i will.

will this bug get fixed tho ? i'v payed hard earned money for this just so
you know .. i may have to move which is something i definitely don't want
to do but.

**Comment by DanielnetoDotCom** [comment]
I really never seen this happened before, and I could not reproduce it.

**Comment by joey2354** [comment]
ok, well we'll see if it happens again then .. lets hope not, i love this
platform it would be a shame.



thanks for the help ... have a nice day :)
