### ISSUE TITLE
No Encoder Quality Settings available 

### ISSUE THREAD

**Issue by davidjmaxey** [DanielnetoDotCom/YouPHPTube-Encoder#58]
I just noticed that I no longer have access to the configurations tab in the Encoder queue area. At one point I could see the different settings and resolutions the encoder was using and tweak as needed. Now this tab is completely gone. Thoughts on what to check?
![screen shot 2018-04-23 at 3 26 34 pm](https://user-images.githubusercontent.com/13489763/39148614-bf93d712-470a-11e8-93e2-966475861ba4.png)

**Comment by DanielnetoDotCom** [comment]
Check your encoder database ->streamers table

**Comment by davidjmaxey** [comment]
Thanks, that worked.

**Comment by DanielnetoDotCom** [comment]
Great
