### ISSUE TITLE
Add new encoding quality

### ISSUE THREAD

**Issue by poulpito** [DanielnetoDotCom/YouPHPTube-Encoder#59]
Hi,

sorry if it's already mentioned somewhere but i was not able to find the information :)  
is there a quick way to add new encoding setting  like a checkbox FHD  and a new ffmpeg setting for 1080p encoding for example ?  or are we limited to 3 quality settings ? 
haven't look yet in views / configuration   only in DB

**Comment by DanielnetoDotCom** [comment]
Hi @poulpito 

Yes we can have max 3 resolution, but you can change them on Encoder configuration.

![image](https://user-images.githubusercontent.com/18009293/39243747-f47e9e5c-4864-11e8-8c17-99f8c34dc7b1.png)

**Comment by poulpito** [comment]
Thanks for comment
I was asking if there is an easy way to add more option 
low sd HD fhd for example :) and if it's in the pipe

**Comment by DanielnetoDotCom** [comment]
@poulpito sorry, there is not such option. and we are not working on it at the moment

**Comment by poulpito** [comment]
i'll have a look, if i came with something good i will create a pull request 
thanks :)
