### ISSUE TITLE
Encoder options missing.

### ISSUE THREAD

**Issue by bytepoet** [DanielnetoDotCom/YouPHPTube-Encoder#6]
![image](https://user-images.githubusercontent.com/8586452/29522952-400c5a2a-869c-11e7-8bd8-d81518d6db7c.png)

Where can i choose encoder options? I recall in the last version that i was able to modify all the individual encoder settings to speed up the process at the expense of file size.  Has this been removed or hidden to the uploader?

**Comment by DanielnetoDotCom** [comment]
I have to check why some people is happening this.
But to fix it try to edit some register of your database...
Go to the `youPHPTube-Encoder`.streamers table and change the column isAdmin to 1
It will make your user admin of the encoder and enable all options

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
