### ISSUE TITLE
bulk encoding request anyway to encode multiple files

### ISSUE THREAD

**Issue by loso20p** [DanielnetoDotCom/YouPHPTube-Encoder#65]
anyway to encode more than one file at a time at least an option?

**Comment by DanielnetoDotCom** [comment]
sorry, it does not

**Comment by loso20p** [comment]
so will it ever or does sumone know how to?

**Comment by DanielnetoDotCom** [comment]
It is not good to be made. encode 2 at the same time will not speed it up.

you processor will takes double of the time to get the job done

**Comment by fsardillopiz** [comment]
Instead of multiple files in only an encoder, It is possible to have multiple encoders /servers serving to a unique streamer? How can I do that? Regards.

**Comment by DanielnetoDotCom** [comment]
Yes

For this I use https://github.com/DanielnetoDotCom/YouPHPTube-Encoder-Network

we do not have an installer for it but you can see it working here https://network.youphptube.com/

We are using it on some clients only.

**Comment by DanielnetoDotCom** [comment]
Looks like you have an error on your SSL

also this error: `PHP Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/html/pakeveas-encoder/objects/Encoder.php:696`

Try to google and fix it;

**Comment by fsardillopiz** [comment]
Thank you very much for your answer, it works. now I have to work wth the encoder network. And the high delay when live streaming using OBS, by the way can you help me with that?. Regards

**Comment by DanielnetoDotCom** [comment]
about the livestream delay, try to ask for help on the Nginx RTMP  https://github.com/arut/nginx-rtmp-module
