### ISSUE TITLE
Encoder issue - Hangs during processing

### ISSUE THREAD

**Issue by Slideboarding** [DanielnetoDotCom/YouPHPTube-Encoder#7]
I am having trouble getting the encoder to work. I downloaded it...got it installed. When I go to upload or grab a video from YouTube, I get to 100% of the download...but don't get to any encoding.  (When i go to my stream site, I can see a video file there, but it never gets encoded and I get an EE:EE error over the duration and the "preview" shows static as if it never got encoded.)   When i try to upload a video from my computer or phone, it hangs during the encoding process.  

When I encode from the public one that is provided, I get really pixelated versions of the videos. Any advice? Thanks...

**Comment by DanielnetoDotCom** [comment]
About the public encoder, it is a tiny shared server, not much resources. that is why it is in a low resolution and takes some time to encode.

about the encoder you have installed, there is an URL i can check how is going?
could you check the log file? the log file is on [encoder-dir]/videos/youphptube.log

I guess you miss the libimage-exiftool-perl installation
Check it here https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x---For-YouPHPTube-Encoder

**Comment by Slideboarding** [comment]
Well... that's embarrassing... Missed an entire section of your installation guide.  Sorry about that.  I have installed the needed dependent programs and all is working now.  Thanks for you help.  

...Aaron

**Comment by DanielnetoDotCom** [comment]
I am glad it helps :) I will close it now

**Comment by alegiovannelli** [comment]
I have the same error. The section of installation guide is satisfait.

Log error

 {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
 YouPHPTube-Encoder sending file to http://www.axgio.net/youtube/youPHPTubeEncoder.json
 YouPHPTube-Encoder reading file from 
 YouPHPTube-Streamer answer {"error":false,"video_id":26}
Getting Video File http://www.axgio.net/youtube_encoder/videos/original_YPTuniqid59b2bc2abf58d473900440_YPTuniqid_59c113ca5ff417.25427726

Thank you in advance

**Comment by DanielnetoDotCom** [comment]
Sorry Alegio, are you not able to encode files?

**Comment by alegiovannelli** [comment]
No, only some mp4 files hangs to encode.
Are files with dimension up to 300 megabytes.

**Comment by DanielnetoDotCom** [comment]
what encoder are you using? the public one or did you install your own encoder?
if it is your encoder, can you check the [encoder-dir]/videos/youphptube.log file?
