### ISSUE TITLE
Encoder not getting past Uploading

### ISSUE THREAD

**Issue by siniztr** [DanielnetoDotCom/YouPHPTube-Encoder#72]
Busy testing the youPHPtube installation with encoder, and while using the Encoder, I can upload the video to the encoder, but it doesn't go further than there.
![encoder](https://user-images.githubusercontent.com/22732606/41507111-255be7d2-722c-11e8-9a32-342b5c040b7b.jpg)
I have tried with the file name as is (includes dots, brackets, etc) and I have tried a file name with just words and spaces. Both file types was mkv. 
When I look into the folder where the videos are stored, I see the names of the files uploaded, but not usable files.
![encoder_ssh](https://user-images.githubusercontent.com/22732606/41507130-8198a602-722c-11e8-9fbe-8c293d090c1f.jpg)
All requirements for the encoder has been installed and all required changes to both file/folder permissions and php.ini have been made as instructed per the installation.
![encoder2](https://user-images.githubusercontent.com/22732606/41507136-bd4ad698-722c-11e8-949c-5f96f6b51803.jpg)

Please note: the files I am testing it with are indeed copyrighted shows, but I am just using them for testing purposes only. These files will not be made publicly available, nor will they be used for any illegal means what so ever. It is being done for testing purposes alone to test the full capability of both the streaming site and the encoder. Once I am done with the testing of the system, both the files I used to test, and the files located on the streaming site (stored and kept local) will be deleted.

**Comment by DanielnetoDotCom** [comment]
Can you please check your encoder log file?

**Comment by DanielnetoDotCom** [comment]
I can see this in your log file PHP Fatal error: Uncaught Error: Call to undefined function curl_init() 

Check this https://stackoverflow.com/questions/6382539/call-to-undefined-function-curl-init

**Comment by siniztr** [comment]
Ok, that resolved the CURL issue, but I am still not able to encode. I am still getting this error: 

> YouPHPTube-Encoder sending file to http://192.168.1.16/youPHPTubeEncoder.json

When I checked, there is no youPHPTubeEncoder.json file in the main folder or in the encoder folder.

**Comment by DanielnetoDotCom** [comment]
Not suppose to have this file, it is resolved by .htaccess file .

Delete your log files (encoder and streamer)

Try to upload again and share the log file with us

**Comment by siniztr** [comment]
This is the log file in case you still need it:
[17-Jun-2018 14:19:06 Europe/Berlin] MP4 All
[17-Jun-2018 14:19:06 Europe/Berlin] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
[17-Jun-2018 14:19:06 Europe/Berlin] YouPHPTube-Encoder sending file to http://192.168.1.16/youPHPTubeEncoder.json
[17-Jun-2018 14:19:06 Europe/Berlin] YouPHPTube-Encoder reading file from
[17-Jun-2018 14:19:06 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/encoder/objects/Encoder.php:558
Stack trace:
#0 /var/www/html/encoder/view/upload.php(69): Encoder::sendFile('', 0, 'mp4', Object(Encoder))
#1 {main}
  thrown in /var/www/html/encoder/objects/Encoder.php on line 558

**Comment by DanielnetoDotCom** [comment]
The .htaccess I have mention is the streamer .htaccess 
I still seeing the same php error as before . Did you restart apache?

You need to fix the curl_init() issue first.

This error is related to your server installation , not YouPHPTube code

**Comment by siniztr** [comment]
Ok I was able to resolve the issue. For some reason after installing the php-curl to resolve the undefined function curl_init() error, a simple 

> service apache restart
wasn't enough. I did a server restart and suddenly everything was working fine. File is encoding now. Will get back if I run in to any other problems.

**Comment by DanielnetoDotCom** [comment]
Great, please close this issue if you done

**Comment by Chandrakant279** [comment]
hey,
When I upload the video again showing this error. Please help me out

 Execute code error "Array\n(\n)\n" 
 Code: ffmpeg -i /opt/lampp/htdocs/vs_enc/videos/1_tmpFile.mp4 -vf scale=-2:360 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y /opt/lampp/htdocs/vs_enc/videos/1_tmpFile_converted_Low.mp4

**Comment by DanielnetoDotCom** [comment]
@Chandrakant279 execute the code manually and check the error

`ffmpeg -i /opt/lampp/htdocs/vs_enc/videos/1_tmpFile.mp4 -vf scale=-2:360 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y /opt/lampp/htdocs/vs_enc/videos/1_tmpFile_converted_Low.mp4`

**Comment by tilicarforever** [comment]
Fix for youPHPTubeEncoder.json missing.

go to Encoder/objects/Encoder.php at line 731

`$target = $youPHPTubeURL . "youPHPTubeEncoder.json";`

and replace with

`$target = $youPHPTubeURL . "aVideoEncoder.json";`

somehow the zip download offers the old files. If you go to Git files individualy, you din't find this line because is changed with 
`$target = $aVideoURL . "aVideoEncoder.json";` at line 802.

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo-Encoder/issues/281
