### ISSUE TITLE
Can't make site configuration changes

### ISSUE THREAD

**Issue by cbranje** [DanielnetoDotCom/YouPHPTube-Encoder#76]
Hi

I've installed everything and uploaded two videos, but when I attempt to make Site Configuration changes it gets stuck at "processing . . . ".

Thanks,
Carmen

**Comment by cbranje** [comment]
I tried again without symbols in my password, but same problem. Can't make any changes to system configuration.

**Comment by DanielnetoDotCom** [comment]
Check your log file.

Also check for javascript errors

**Comment by cbranje** [comment]
I'm getting this in javascript when I try and save a configuration?

**Comment by cbranje** [comment]
What should the permissions be?

**Comment by cbranje** [comment]
From the Dev Console in chrome:

"Failed to load resource: the server responded with a status of 403 (Forbidden)"

**Comment by DanielnetoDotCom** [comment]
I know it is form there, but it should not happened, something is wrong on your server, maybe a file missing or some misconfiguration

**Comment by cbranje** [comment]
Is configuration apache part of the installation process?? I thought I saw something in the install docs, but I can't remember. . .

**Comment by DanielnetoDotCom** [comment]
This Forbidden error is new for me, I have never seen it before

**Comment by cbranje** [comment]
I got it working now! You were correct it was a server configuration issue. I turned off modsecurity as recommended by my sys admin and it works now.
