### ISSUE TITLE
Audio garbleld when encoding from Youtube

### ISSUE THREAD

**Issue by siniztr** [DanielnetoDotCom/YouPHPTube-Encoder#79]
I recently moved my test install to a new location (new vmware on my computer) and upgraded both the streamer and encoder site. Both work fine, but I notice now that when I encode a video from youtube, the audio is garbled and the video doesn't always work properly.

I did two examples on my test-setup, and in one the video was fine, the audio was really garbled. The second video I tried with there was no video and no audio.

Uploaded video file from computer works fine. 

Nothing to report in the error.log from Apache2.

Background information:
Ubuntu 18.04 running apache2 > http2, fastCGI and PHP7.2-FPM 
Vserver is assigned 2 cores and 2GB ram, PHP assigned max_execution_time of 9000 and everything else by the book.

**Comment by DanielnetoDotCom** [comment]
I have never seen this before , try to use your youtube-dl command line to manually download your video

**Comment by siniztr** [comment]
I tried the command line as you advised, and got the same thing. Could it be that maybe the video I chose has some kind of data protection from doing exactly what I am doing? 

I will try again with another random video and see what happens.

**Comment by siniztr** [comment]
Hmm I downloaded another video, and it works fine. Seems that youtube actually incorporated some kind of copyright protection embedded into some videos. Didn't even know that was possible. 
Closing the ticket.
