### ISSUE TITLE
youtube downloading feature often doesn't work, but sometimes does

### ISSUE THREAD

**Issue by OhioVR** [DanielnetoDotCom/YouPHPTube-Encoder#82]
Hi Daniel,

I'm experimenting with your youtube import feature in the encoder and it during the process on the encoder it looks like everything is working but when it is done, on the streamer site it lists the video length as EE:EE:EE. Looking in the storage folder it has a thumb but no video files. I've noticed that all of the videos that were music video in origin failed to move over correctly. I thought it might be something to do with the aspect ratio but I've found that normal 16:9 videos also fail. I'm using the latest youtube-dl. I used youtube-dl on my workstation then dropped the file into the encoder that way and it also failed. All of my own files work, I just can't get youtube downloaded files to work. I setup a test youphptube instance just for testing this function to get some fresh logs. I've attached my streamer and encoder logs to this message. Thank you for your hard work!
[(encoder) youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/files/2281218/encoder.youphptube.log)
[(streamer) youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/files/2281219/streamer.youphptube.log)

I have seen the importer work though on one example I tried (but wasn't music related). Is there some kind of copy restriction in there?

**Comment by DanielnetoDotCom** [comment]
I found this on your Streamer 

`PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\HttpException: Route "/status/" or method "get" not allowed. in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:287`


And this on your encoder: **413 Request Entity Too Large**

Looks like is something on your network, try to google to find the solution

**Comment by OhioVR** [comment]
Thanks Daniel this at least rules out a problem with your code. There is probably something I'm doing wrong with my reverse proxy container. Shouldn't be hard to fix. I'll get it figured out in day or two, but first I want to see if I can get my containerized rtmp nginx server working with youphptube.

**Comment by OhioVR** [comment]
I fixed this issue by setting this value in an nginx site conf for my reverse proxy:

client_max_body_size 0;

Now it is good to go.
