### ISSUE TITLE
Error: Sorry! This user can not upload files

### ISSUE THREAD

**Issue by md97** [DanielnetoDotCom/YouPHPTube-Encoder#83]
I just installed the encoder and I'm getting the error "Sorry! This user can not upload files" whenever I try to upload a video. Even on the admin account. In my configuration settings I have the permissions to upload set... Not sure where I went wrong. 
Direct MP4 upload works, just not the encoder.
Any suggestions?

**Comment by md97** [comment]
Okay, so when I click the encoder link of my site it brings me to the encoder page where I am logged in as I was on the streamer site. If I try upload anything I get the error mentioned above, BUT if I log out and log in again ON the streamer site I can upload. So is this a bug?

**Comment by DanielnetoDotCom** [comment]
Please check your log file

**Comment by mcuix** [comment]
I seem to be experiencing the same problem, which is perhaps related to the issue that I raised #87 .
When I am logged in as an admin on the streamer, I choose the Encoder
![image](https://user-images.githubusercontent.com/20878779/44679661-e36a7f80-aa3b-11e8-9449-733f0a85f6fa.png)
..which redirects me to my encoder server
![image](https://user-images.githubusercontent.com/20878779/44679719-01d07b00-aa3c-11e8-91d7-68ffe1146e9a.png)

**Comment by DanielnetoDotCom** [comment]
I have answered on the other issue

**Comment by mcuix** [comment]
I fixed the issue by replacing my htacces file with the _classical_ version.

**Comment by DanielnetoDotCom** [comment]
ok, great
