### ISSUE TITLE
Configuration issue/Security issue: should use PHP getenv() function instead of hardcoding values in configuration.php

### ISSUE THREAD

**Issue by FlatEarthTruther** [DanielnetoDotCom/YouPHPTube-Encoder#84]
The application should use [PHP getenv() function](https://secure.php.net/manual/en/function.getenv.php) and environment variables should be set in NGINX or Apache website config, instead of hardcoding values in configuration.php

doing this can potentially protect the site from security issues in regards to when server doesn't parse PHP code and shows raw files code exposing all configuration values along with the code, including password, usernames and other private values.

**Comment by FlatEarthTruther** [comment]
```php
$global['webSiteRootURL'] = getenv('ENCODER_ROOT_URL');   // 'https://encoder.example.com/';
$global['systemRootPath'] = getenv('ENCODER_ROOT_PATH');  // '/var/www/html/YouPHPTube-Encoder/';

$mysqlHost = getenv('MYSQL_HOST');                        //  'localhost';
$mysqlPort = getenv('MYSQL_PORT');                        //  '3306';
$mysqlUser = getenv('MYSQL_USER');                        //  'youphptube';
$mysqlPass = getenv('MYSQL_PASS');                        //  'youphptube';
$mysqlDatabase = getenv('MYSQL_DB_NAME');                 //  'youPHPTube-Encoder';
```

**Comment by FlatEarthTruther** [comment]
[The Very Best of K-Rino](https://www.youtube.com/watch?v=R_DtZFL_ar0)

**Comment by DanielnetoDotCom** [comment]
Lets keeping track this here https://github.com/DanielnetoDotCom/YouPHPTube/issues/977#issuecomment-414108703
