### ISSUE TITLE
Delivery of purchased plugins?

### ISSUE THREAD

**Issue by mcuix** [DanielnetoDotCom/YouPHPTube-Encoder#85]
How are the paid plugins delivered after purchase?

**Comment by DanielnetoDotCom** [comment]
Hi

After the purchase, go back to the easytube.club and you will see a download button on the plugin.

Please confirm if you found

**Comment by mcuix** [comment]
Found it. Thx

**Comment by DanielnetoDotCom** [comment]
Great
