### ISSUE TITLE
Custom script error

### ISSUE THREAD

**Issue by arrna** [DanielnetoDotCom/YouPHPTube-Encoder#86]
Hello. Everything works normally. But when I write this in "HD"
`ffmpeg -y -i {$pathFileName} -strict experimental -c:v libx264 -preset medium -b:v 5000K -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2, subtitles='/var/www/html/uploads/1.ass'" -pass 1 -sn -an -f mp4 -threads 0 NUL && ffmpeg -y -i {$pathFileName} -strict experimental -c:v libx264 -preset medium -b:v 5000K -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2, subtitles='/var/www/html/uploads/1.ass'" -map 0:v:0? -map_chapters 0 -pass 2 -c:a aac -b:a 256k -map 0:a? -map_metadata 0 -f mp4 -threads 0 {$destinationFile}`

youphptube.log

> [23-Aug-2018 18:27:30 UTC] PHP Warning:  file_get_contents(/var/www/html/YouPHPTube-Encoder/videos/9_tmpFile_progress.txt): failed to open stream: No such file or directory in /var/www/html/YouPHPTube-Encoder/objects/functions.php on line 28
[23-Aug-2018 18:27:30 UTC] PHP Warning:  file_get_contents(/var/www/html/YouPHPTube-Encoder/videos/9_tmpFile_progress.txt): failed to open stream: No such file or directory in /var/www/html/YouPHPTube-Encoder/objects/functions.php on line 43

and upload remains %99
What is the problem?
Thanks

**Comment by DanielnetoDotCom** [comment]
the warning on tmpFile_progress.txt is normal, but I cant tell you what is wrong on your ffmpeg code.
Try to manually run it and see what was wrong

**Comment by arrna** [comment]
Thanks for the answer
The script works when I try it manually. 
But there is something like this:
![1](https://user-images.githubusercontent.com/12846006/44582623-e13dc200-a7aa-11e8-8268-8b051f6c1dd5.png)
but phpmyadmin:
![2](https://user-images.githubusercontent.com/12846006/44582643-f0bd0b00-a7aa-11e8-8ff3-7f11cc36bc0b.JPG)
I am waiting for your reply

**Comment by DanielnetoDotCom** [comment]
I can see it, I am not sure why you are using this custom script, but looks like the double quotes are the key

Try to replace the " for \"

**Comment by arrna** [comment]
> Try to replace the " for \"

I didnt understand this. What did you mean?
