### ISSUE TITLE
Encoder - "This Streamer site is not allowed"

### ISSUE THREAD

**Issue by Gooseblues** [DanielnetoDotCom/YouPHPTube-Encoder#88]
Im getting this error when logging in to the my local encoder.   I did figure out how to get in.  At the sign in page, i change the YouPHPTube Streamer Site from http://media/YouPHPTube/ to HTTP://media/YouPHPTube.

Where can I change that so it automatically goes to HTTP instead of http?

Thanks.
![screenshot from 2018-08-29 15-45-04](https://user-images.githubusercontent.com/42819060/44814513-8b01c200-aba2-11e8-9251-0701baec9c10.png)

**Comment by DanielnetoDotCom** [comment]
This is the URL you defined on the videos/configuration.php file

**Comment by Gooseblues** [comment]
That was it.  Thank you.

**Comment by DanielnetoDotCom** [comment]
Great
