### ISSUE TITLE
site banned

### ISSUE THREAD

**Issue by restriato** [DanielnetoDotCom/YouPHPTube-Encoder#92]
I would like to know why my site was banned ... The videos that are are of own authors etive that install several times the encoder because it was not able to upload the videos .. my IP is 192.227.118.21 and the domain videos.modulos. mobi/peduc

Thanks
Renata

**Comment by DanielnetoDotCom** [comment]
what is your YouPHPTube Domain?

**Comment by restriato** [comment]
videos.modulos. mobi/peduc

**Comment by DanielnetoDotCom** [comment]
Hi

Sorry but I am not sure what is happening but your site is not on the ban list https://search.youphptube.com/blackListed

What encoder are you using?

The public encoder?

**Comment by restriato** [comment]
No .. I use encoder itself, which is installed in videos.modulos.mobi/encoder-peduc
![screenshot_35](https://user-images.githubusercontent.com/34867124/45763062-1c92ab80-bc06-11e8-9676-3efda7eafce2.jpg)

**Comment by DanielnetoDotCom** [comment]
Sorry for that I am reviewing it.

**Comment by DanielnetoDotCom** [comment]
Ok, I found what happened.

For some reason your site was inactive (NOT banned), I just activate it again.

but the Ban request has a cache that expires in 1 hour.

you can try to restart your server to try to clear that cache.

**Comment by restriato** [comment]
How do I activate? I shut down the server, cleaned the cache, and nothing changed.

**Comment by DanielnetoDotCom** [comment]
The cache I am talking about is your /tmp dir

your encoder create some cache there

**Comment by DanielnetoDotCom** [comment]
I just check it, looks like you can login now

**Comment by restriato** [comment]
Now I got .. updated the platform by git.pull and came back

**Comment by DanielnetoDotCom** [comment]
great
