### ISSUE TITLE
Error on upload

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube-Encoder#96]
[13-Nov-2018 11:25:53 America/New_York] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/encoder/objects/Encoder.php:696
Stack trace:
#0 /var/www/html/encoder/view/upload.php(74): Encoder::sendFile('', 0, 'mp4', Object(Encoder))
#1 {main}
  thrown in /var/www/html/encoder/objects/Encoder.php on line 696

**Comment by DanielnetoDotCom** [comment]
Try to google for that, I am sure you can find a solution

**Comment by DanielnetoDotCom** [comment]
I close because this  issue is not related to youphptube

**Comment by Puyodead1** [comment]
think its fixed, thanks
